// Generated by Wrangler on Fri May 17 2024 21:14:06 GMT-0600 (Mountain Daylight Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	NODE_ENV: "development";
	R2_PROXY_URL: "https://r2.aries.fyi";
	files: R2Bucket;
}
