#:schema node_modules/wrangler/config-schema.json
name = "files-viewer"
compatibility_date = "2024-04-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[r2_buckets]]
binding = "files"
bucket_name = "files"
